### ISSUE TITLE
GCS configuration

### ISSUE THREAD

**Issue by atamano** [getlago/lago-helm-charts#128]
Hello!
Do you have any plans to add GCS configuration in the future? Thank you!

**Comment by jdenquin** [comment]
hello @atamano, is there any specific configuration for GCS in mind?

**Comment by jdenquin** [comment]
https://docs.getlago.com/guide/self-hosted/docker#google-cloud-service-cloud-storage is not what you need?

**Comment by atamano** [comment]
yes, in this project there are parameters like `global.s3. enabled` `global.s3.bucket` (...)  for S3 so I was expecting the same for GCS

**Comment by atamano** [comment]
I drafted a quick and dirty example (not sure it works)
https://github.com/getlago/lago-helm-charts/commit/ef31fa3b678118506127ab51eea1550d30404e46

**Comment by KhadijaBenAmmar** [comment]
Hello,
Any updates on this issue?

**Comment by ilya-vasiuk** [comment]
@atamano you can always use [Interoperability API](https://cloud.google.com/storage/docs/interoperability). Just create service account HMAC and use next config:
```
s3:
  enabled: true
  endpoint: https://storage.googleapis.com
  region: your_bucket_region
  bucket: your_bucket_name
  accessKeyId: your_HMAC_access_id
  secretAccessKey: your_HMAC_secret
```
