### ISSUE TITLE
Unable to run lago in my EKS

### ISSUE THREAD

**Issue by nirberko** [getlago/lago-helm-charts#154]
i've added the `https://charts.getlago.com` repository to Helm
and when I'm trying to deploy the Lago deployment chart:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.lago.name }}
  namespace: {{ .Values.lago.namespace }}
spec:
  replicas: {{ .Values.lago.replicas }}
  selector:
    matchLabels:
      app: lago
  template:
    metadata:
      labels:
        app: lago
    spec:
      containers:
        - name: lago
          image: "charts.getlago.com/{{ .Values.lago.image.repository }}:{{ .Values.lago.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: server-config-{{ .Values.environment }}
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: server-config-{{ .Values.environment }}
                  key: POSTGRES_PORT
            - name: POSTGRES_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: server-config-{{ .Values.environment }}
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: server-secret-{{ .Values.environment }}
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: lago
```

I get this error:
```
Failed to pull image "charts.getlago.com/lago:latest": rpc error: code = NotFound desc = failed to pull and unpack image "charts.getlago.com/lago:latest": failed to resolve reference "charts.getlago.com/lago:latest": charts.getlago.com/lago:latest: not found
```

for the `image.repository` I tried `lago/lago` and also `lago`. I also tried with and without `charts.getlago.com` before the repository name.

thanks for your help 🥇
