### ISSUE TITLE
Failed to SignUp 

### ISSUE THREAD

**Issue by jannikstdl** [getlago/lago-helm-charts#56]
Hello,

if i want to sign up on my deployed applicaltion on K8s i get this error:

![image](https://github.com/getlago/lago-helm-charts/assets/69747628/c54c07e9-aa97-4edd-80e1-33060cda2632)

I haven't changed any vaule except the required `frontUrl ` and `apiUrl ` + i added an internal ingress on top.

Ingress looks like this:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lago-ingress
  namespace: namespace-one
  annotations:
    kubernetes.io/ingress.class: nginx-mpls
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: billing.ai.company.intern
      http:
        paths:
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: lago-front-svc
                port:
                  number: 80
  tls:
    - hosts:
        - billing.ai.company.intern
      secretName: tls-secret
```
